version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=legalist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  scrapy:
    build: .
    command: crontab -l
    volumes:
      - .:/legalist
    depends_on:
      - db
      - redis
    network_mode: "host"

  redis:
    image: redis
    ports:
     - "6379:6379" # added port for external db provisioning
